# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d73f59107b4563c7b267f93478f18c2e0f2914e2bf2e3146e693f286ab47f5f0ed1ea7ecba0f103178b4e5b2127c3f8aea6c3d60fff4594ddd41382e387cd09c

test:
  secret_key_base: f528b9973a604f55f83bb72e7f89902f1035324909786fcc52bc7cd2da99d1d73e82e01a448f0e90d029aab170c5224c3a7f3ed1efda93868a283d90f9894a42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
